version: "3"

services:
  client:
    build: ./src/AprsWeatherClient
    depends_on:
      - server
    ports:
      - "80:80"

  server:
    build: ./src/AprsWeatherServer
    ports:
      - "5148:80"
    environment:
      - APRS_IS_CALLSIGN=${APRS_IS_CALLSIGN}
      - ASPNETCORE_ENVIRONMENT=Development
