version: "3"

services:
  client:
    build:
      dockerfile: ./AprsWeatherClient/Dockerfile
      context: ./src
      args:
        ENVIRONMENT: Development
    depends_on:
      - server
    ports:
      - "80:80"

  server:
    build:
      dockerfile: ./AprsWeatherServer/Dockerfile
      context: ./src
    ports:
      - "5148:80"
    environment:
      - APRS_IS_CALLSIGN=${APRS_IS_CALLSIGN}
      - ASPNETCORE_ENVIRONMENT=Development
