name: AprsWeather
services:
  - name: AprsWeatherServer
    github:
      repo: CBielstein/AprsWeather
      branch: main
      deploy_on_push: false
    dockerfile_path: src/AprsWeatherServer/Dockerfile
    envs:
      - key: APRS_IS_CALLSIGN
        value: ${APRS_IS_CALLSIGN}
        type: GENERAL
        scope: RUN_TIME
    routes:
      - path: /api
static_sites:
  - name: AprsWeatherClient
    github:
      repo: CBielstein/AprsWeather
      branch: main
      deploy_on_push: false
    dockerfile_path: src/AprsWeatherClient/Dockerfile
    output_dir: /app/publish
region: sfo3
domains:
  - domain: hamwx.bielstein.dev
    type: PRIMARY
    wildcard: false
